//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseManagement.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PurchaseManagement.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis    Column.
        /// </summary>
        public static string AnalysisColumn {
            get {
                return ResourceManager.GetString("AnalysisColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Time.
        /// </summary>
        public static string ByTime {
            get {
                return ResourceManager.GetString("ByTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePsw {
            get {
                return ResourceManager.GetString("ChangePsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check input message!.
        /// </summary>
        public static string CheckInputMsg {
            get {
                return ResourceManager.GetString("CheckInputMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check order&apos;ID!.
        /// </summary>
        public static string CheckOrderIDTips {
            get {
                return ResourceManager.GetString("CheckOrderIDTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It needs to restart application to take effect of language setting.(Target : English).
        ///Restart application right now?.
        /// </summary>
        public static string ChineseToEnglishTips {
            get {
                return ResourceManager.GetString("ChineseToEnglishTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Column.
        /// </summary>
        public static string ConditionColumn {
            get {
                return ResourceManager.GetString("ConditionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daliy.
        /// </summary>
        public static string Daliy {
            get {
                return ResourceManager.GetString("Daliy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is {0} item with empty amount, delete it?.
        /// </summary>
        public static string EmptyTipsFormat {
            get {
                return ResourceManager.GetString("EmptyTipsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言更改生效需要重启程序(目标语言：中文).
        ///立即重启程序?.
        /// </summary>
        public static string EnglishToChineseTips {
            get {
                return ResourceManager.GetString("EnglishToChineseTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot connect to server. Contact administrator..
        /// </summary>
        public static string Error0Tips {
            get {
                return ResourceManager.GetString("Error0Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password, please try again..
        /// </summary>
        public static string Error1045Tips {
            get {
                return ResourceManager.GetString("Error1045Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied for current user to database..
        /// </summary>
        public static string Error1046Tips {
            get {
                return ResourceManager.GetString("Error1046Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food.
        /// </summary>
        public static string Food {
            get {
                return ResourceManager.GetString("Food", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods.
        /// </summary>
        public static string Goods {
            get {
                return ResourceManager.GetString("Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods detail.
        /// </summary>
        public static string GoodsDetail {
            get {
                return ResourceManager.GetString("GoodsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goods ID.
        /// </summary>
        public static string GoodsID {
            get {
                return ResourceManager.GetString("GoodsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handing.
        /// </summary>
        public static string Handing {
            get {
                return ResourceManager.GetString("Handing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide panel.
        /// </summary>
        public static string HidePanel {
            get {
                return ResourceManager.GetString("HidePanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID detail.
        /// </summary>
        public static string IDDetail {
            get {
                return ResourceManager.GetString("IDDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Manage.
        /// </summary>
        public static string InfoManage {
            get {
                return ResourceManager.GetString("InfoManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input right id value!.
        /// </summary>
        public static string InputRightIDTips {
            get {
                return ResourceManager.GetString("InputRightIDTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Title.
        /// </summary>
        public static string InputTitle {
            get {
                return ResourceManager.GetString("InputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert successful!.
        /// </summary>
        public static string InsertSuccessful {
            get {
                return ResourceManager.GetString("InsertSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string Interval {
            get {
                return ResourceManager.GetString("Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember login id.
        /// </summary>
        public static string LogAccount {
            get {
                return ResourceManager.GetString("LogAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login ID.
        /// </summary>
        public static string LoginID {
            get {
                return ResourceManager.GetString("LoginID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Setting.
        /// </summary>
        public static string LoginSetting {
            get {
                return ResourceManager.GetString("LoginSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max amount.
        /// </summary>
        public static string MaxAmount {
            get {
                return ResourceManager.GetString("MaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPsw {
            get {
                return ResourceManager.GetString("NewPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Purchase Order.
        /// </summary>
        public static string NewPurchaseOrder {
            get {
                return ResourceManager.GetString("NewPurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPsw {
            get {
                return ResourceManager.GetString("OldPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string OrderID {
            get {
                return ResourceManager.GetString("OrderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order project detail.
        /// </summary>
        public static string OrderProjDetail {
            get {
                return ResourceManager.GetString("OrderProjDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Project.
        /// </summary>
        public static string OrderProject {
            get {
                return ResourceManager.GetString("OrderProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderProject ID.
        /// </summary>
        public static string OrderProjectID {
            get {
                return ResourceManager.GetString("OrderProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Type.
        /// </summary>
        public static string OrderType {
            get {
                return ResourceManager.GetString("OrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is empty!.
        /// </summary>
        public static string ProjEmptyTips {
            get {
                return ResourceManager.GetString("ProjEmptyTips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchse.
        /// </summary>
        public static string Purchase {
            get {
                return ResourceManager.GetString("Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase ID.
        /// </summary>
        public static string PurchaseID {
            get {
                return ResourceManager.GetString("PurchaseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Management.
        /// </summary>
        public static string PurchaseManagement {
            get {
                return ResourceManager.GetString("PurchaseManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order.
        /// </summary>
        public static string PurchaseOrder {
            get {
                return ResourceManager.GetString("PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase State.
        /// </summary>
        public static string PurchaseState {
            get {
                return ResourceManager.GetString("PurchaseState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real amount.
        /// </summary>
        public static string RealAmount {
            get {
                return ResourceManager.GetString("RealAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real Pay.
        /// </summary>
        public static string RealPay {
            get {
                return ResourceManager.GetString("RealPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Detail.
        /// </summary>
        public static string ReceiptDetail {
            get {
                return ResourceManager.GetString("ReceiptDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptID.
        /// </summary>
        public static string ReceiptID {
            get {
                return ResourceManager.GetString("ReceiptID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search project.
        /// </summary>
        public static string SearchProj {
            get {
                return ResourceManager.GetString("SearchProj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Table.
        /// </summary>
        public static string SearchTable {
            get {
                return ResourceManager.GetString("SearchTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string Specifications {
            get {
                return ResourceManager.GetString("Specifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        public static string StaffID {
            get {
                return ResourceManager.GetString("StaffID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics   Column.
        /// </summary>
        public static string StatsColumn {
            get {
                return ResourceManager.GetString("StatsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubTitle.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Detail.
        /// </summary>
        public static string SupplierDetail {
            get {
                return ResourceManager.GetString("SupplierDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier ID.
        /// </summary>
        public static string SupplierID {
            get {
                return ResourceManager.GetString("SupplierID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Type.
        /// </summary>
        public static string TimeType {
            get {
                return ResourceManager.GetString("TimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tips.
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total prices.
        /// </summary>
        public static string TotalPrices {
            get {
                return ResourceManager.GetString("TotalPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string Transform {
            get {
                return ResourceManager.GetString("Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Successful!.
        /// </summary>
        public static string UpdateSuccessful {
            get {
                return ResourceManager.GetString("UpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WareHousing.
        /// </summary>
        public static string WareHousing {
            get {
                return ResourceManager.GetString("WareHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehousing Detail.
        /// </summary>
        public static string WarehousingDetail {
            get {
                return ResourceManager.GetString("WarehousingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehousing ID.
        /// </summary>
        public static string WarehousingID {
            get {
                return ResourceManager.GetString("WarehousingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wareroom ID.
        /// </summary>
        public static string WareroomID {
            get {
                return ResourceManager.GetString("WareroomID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yuan.
        /// </summary>
        public static string Yuan {
            get {
                return ResourceManager.GetString("Yuan", resourceCulture);
            }
        }
    }
}
